apiVersion: v1
kind: Namespace
metadata:
  name: agent2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent2
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/Sphinxgaia/lechatbotte.git
    targetRevision: HEAD
    path: apps/01-agent2
  destination:
    server: https://kubernetes.default.svc
    namespace: agent2
  syncPolicy:
    automated: {}