apiVersion: v1
kind: Namespace
metadata:
  name: agent1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent1
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/Sphinxgaia/lechatbotte.git
    targetRevision: HEAD
    path: apps/02-agent1
  destination:
    server: https://kubernetes.default.svc
    namespace: agent1
  syncPolicy:
    automated: {}