apiVersion: v1
kind: Namespace
metadata:
  name: plugin2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin2
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/Sphinxgaia/lechatbotte.git
    targetRevision: HEAD
    path: apps/04-plugin2
    plugin:
      env:
        - name: VAULT_ADDR
          value: http://vault.vault.svc:8200
        
        - name: ARGOCD_ENV_AVP_TYPE
          value: vault
        - name: ARGOCD_ENV_AVP_AUTH_TYPE
          value: k8s
        - name: ARGOCD_ENV_AVP_K8S_ROLE
          value: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: plugin2
  syncPolicy:
    automated: {}