apiVersion: v1
kind: Namespace
metadata:
  name: vsoc2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vsoc2
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/Sphinxgaia/lechatbotte.git
    targetRevision: HEAD
    path: apps/03-vsoc2
  destination:
    server: https://kubernetes.default.svc
    namespace: vsoc2
  syncPolicy:
    automated: {}