apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "echo1.192.168.1.31.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-deployment
            port:
              number: 80