kind: Secret
apiVersion: v1
metadata:
  name: example1
type: Opaque
data:
  username: <path:secret/data/test2/config#username> # same as <username>
  password: <path:secret/data/test2/config#password> # same as <password>