apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: vso-example
spec:
  serviceAccount: demo-static-app
  containers:
  - name: alpine
    image: alpine
    args:
    - sleep
    - "1000000"