apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-kv-app2
  namespace: vso-example
spec:
  namespace: admin/ns2
  type: kv-v2

  # mount path
  mount: k8s-secrets

  # path of the secret
  path: k8s-asp/vso-example/config

  # dest k8s secret
  destination:
    name: secretkv2
    create: true
    transformation:
      excludeRaw: true
      # excludes:
      #  - .*
      # templates:
      #   toto: 
      #     text: "{{- printf \"password=%s\" (get .Secrets \"pass\") -}}"

  # static secret refresh interval
  # refreshAfter: 1h # enterprise
  refreshAfter: 30s # oss
  hmacSecretData: true
  # Name of the CRD to authenticate to Vault
  vaultAuthRef: vault-auth
  # vaultConnectionRef: app/static-default
  # syncConfig:
  #   instantUpdates: true
