apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: vso-example
  name: demo-static-app
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: vso-example
  name: vault-auth
spec:
  vaultAuthGlobalRef:
    name: vault-auth-global
    namespace: vso-admin
  kubernetes:
    role: test-k8s
    serviceAccount: demo-static-app
