apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault-auth-delegator
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: vault-auth-delegator
  annotations:
    kubernetes.io/service-account.name: vault
type: kubernetes.io/service-account-token